RewardPercentage: 50.0
Rewards:
  - "eco give %player% 10"
  - "tokenadmin add %player% 10"
  - "give %player% diamond 1"

RewardLore:
  "eco give %player% 10": "Receive 10 economy points"
  "tokenadmin add %player% 10": "Receive 10 tokens"
  "give %player% diamond 1": "Receive a diamond"
