main: server.alanbecker.net.Main
name: ABMCMineCrates
version: 1
api-version: 1.19

commands:
  minecratereload:
    description: Reloads the MineCrate configuration.
    permission: minecrate.reload
